"""Add function to delete a playlist and its songs

Revision ID: 58dccb911dae
Revises: 698550becfb9
Create Date: 2017-11-08 15:31:43.111628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58dccb911dae'
down_revision = '698550becfb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('songs_playlist_id_fkey', 'songs', type_='foreignkey')
    op.create_foreign_key(None, 'songs', 'playlists', ['playlist_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'songs', type_='foreignkey')
    op.create_foreign_key('songs_playlist_id_fkey', 'songs', 'playlists', ['playlist_id'], ['id'])
    # ### end Alembic commands ###
