"""Create songs table wwith a one to many relationship with playlists table

Revision ID: 698550becfb9
Revises: 2f1c22fb90f5
Create Date: 2017-11-08 11:18:09.880985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698550becfb9'
down_revision = '2f1c22fb90f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('songs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('song_path', sa.String(), nullable=True),
    sa.Column('playlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('songs')
    # ### end Alembic commands ###
